name: Lint PR title

on:

  pull_request_target:
    types: [opened, reopened, synchronize, edited, ready_for_review]

jobs:

    lint:
      runs-on: ubuntu-latest
      steps:
      - uses: amannn/action-semantic-pull-request@v3.2.5
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          subjectPattern: ^(?![A-Z]).+$
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}" should start with a lowercase character.